# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: Build
# Multi-stage Dockerfile for mcp-abap-adt

# -----------------------
# Builder stage
# -----------------------
FROM node:18-alpine AS builder

WORKDIR /app

# Install build dependencies (use package-lock when available)
COPY package.json package-lock.json* ./
RUN npm ci --prefer-offline --no-audit --progress=false

# Copy sources and build
COPY . .
RUN npm run build


# -----------------------
# Runtime stage
# -----------------------
FROM node:18-alpine AS runtime

WORKDIR /app

# Minimal production environment
ENV NODE_ENV=production

# Install only production dependencies
COPY package.json package-lock.json* ./
RUN npm ci --only=production --prefer-offline --no-audit --progress=false || true

# Copy built artifacts from builder
COPY --from=builder /app/dist ./dist

# Create a non-root user and use it
RUN addgroup -S app && adduser -S app -G app || true
USER app

# Default port for remote adapter (can be overridden with MCP_REMOTE_PORT or PORT)
EXPOSE 6969

CMD ["node", "dist/index.js"]
